spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-com.ibm.esw.leo.spring.security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456